// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Data;
using Azure.DataApiBuilder.Config.DatabasePrimitives;
using Azure.DataApiBuilder.Config.ObjectModel;
using Azure.DataApiBuilder.Core.Custom;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Azure.DataApiBuilder.Service.Tests.UnitTests
{
    /// <summary>
    /// Unit tests for injecting tenant JSON attributes into an entity's SourceDefinition as
    /// VirtualColumnDefinition entries (MsSqlTenantSchemaExtensions.ApplyTenantVirtualColumns).
    ///
    /// This injection is what makes a dynamic attribute a first-class field: DAB's GraphQL schema,
    /// REST field validation, default projection, filter model and wildcard field authorization all
    /// enumerate SourceDefinition.Columns. The tests therefore focus on which fields are accepted,
    /// which are safely skipped, and how a generated dab-config mapping is reconciled.
    /// </summary>
    [TestClass, TestCategory(TestCategory.MSSQL)]
    public class TenantSchemaVirtualColumnUnitTests
    {
        private const string TENANT_ID = "TENANT-A";
        private const string ENTITY_NAME = "Assay";
        private const string CONTAINER_COLUMN = "CustomAttributesJson";

        #region Successful injection

        /// <summary>
        /// A well-formed JSON attribute becomes a virtual column keyed by its ApiAlias, carrying the
        /// container column, JSON path and the types derived from its declared DataType.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_ValidJsonAttribute_AddsVirtualColumn()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();

            int injected = sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity: null,
                new[] { CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)") });

            Assert.AreEqual(1, injected);
            Assert.IsTrue(sourceDefinition.Columns.TryGetValue("recoveryRate", out ColumnDefinition? columnDefinition));

            VirtualColumnDefinition virtualColumn = (VirtualColumnDefinition)columnDefinition!;
            Assert.AreEqual("recoveryRate", virtualColumn.ApiAlias);
            Assert.AreEqual(CONTAINER_COLUMN, virtualColumn.ContainerColumnName);
            Assert.AreEqual("$.RecoveryRate", virtualColumn.JsonPath);
            Assert.AreEqual("DECIMAL(18,6)", virtualColumn.SqlReadCastType);
            Assert.AreEqual(typeof(decimal), virtualColumn.SystemType);
            Assert.AreEqual(DbType.Decimal, virtualColumn.DbType);
            Assert.IsTrue(virtualColumn.IsNullable, "A JSON key may simply be absent, so the field must be nullable.");
            Assert.IsFalse(virtualColumn.IsAutoGenerated);
            Assert.IsFalse(virtualColumn.HasDefault);
        }

        /// <summary>
        /// IsReadOnly flows onto the column definition so DAB's existing read-only enforcement rejects
        /// writes with no additional code.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_ReadOnlyField_MarksColumnReadOnly()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("computedGrade", "$.ComputedGrade", "decimal(18,6)") with { IsReadOnly = true };

            sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field });

            Assert.IsTrue(((VirtualColumnDefinition)sourceDefinition.Columns["computedGrade"]).IsReadOnly);
        }

        /// <summary>
        /// IsVisible is front-end form metadata only and must not remove a field from the API surface.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_InvisibleField_IsStillExposed()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("internalNote", "$.InternalNote", "nvarchar") with { IsVisible = false };

            Assert.AreEqual(1, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
            Assert.IsTrue(sourceDefinition.Columns.ContainsKey("internalNote"), "IsVisible is a UI hint, not an API filter.");
        }

        /// <summary>Multiple attributes on one container column are all injected.</summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_MultipleAttributes_AllInjected()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();

            int injected = sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity: null,
                new[]
                {
                    CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)"),
                    CreateJsonAttribute("goldGrade", "$.GoldGrade", "decimal(18,6)"),
                    CreateJsonAttribute("notes", "$.Notes", "nvarchar")
                });

            Assert.AreEqual(3, injected);
            Assert.AreEqual(6, sourceDefinition.Columns.Count, "Three physical columns plus three virtual columns.");
        }

        #endregion

        #region dab-config reconciliation

        /// <summary>
        /// When the config generator also emits a documentation mapping for a virtual column, DAB's
        /// exposed-to-backing map is driven by that mapping. The virtual column must therefore be keyed
        /// by the mapping's backing name, or REST would resolve the alias to a name that is absent from
        /// SourceDefinition.Columns and reject the field.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_ConfigMappingForAlias_KeysColumnByMappingBackingName()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            Entity entity = CreateEntity(mappings: new Dictionary<string, string>
            {
                { "CustomAttributesJson.RecoveryRate", "recoveryRate" }
            });

            sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity,
                new[] { CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)") });

            Assert.IsTrue(
                sourceDefinition.Columns.ContainsKey("CustomAttributesJson.RecoveryRate"),
                "The virtual column must be keyed by the backing name the config mapping declares.");
            Assert.IsFalse(sourceDefinition.Columns.ContainsKey("recoveryRate"));
            Assert.AreEqual("recoveryRate", ((VirtualColumnDefinition)sourceDefinition.Columns["CustomAttributesJson.RecoveryRate"]).ApiAlias);
        }

        /// <summary>A fields[] alias is honored the same way as a legacy mapping.</summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_ConfigFieldAlias_KeysColumnByFieldName()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            Entity entity = CreateEntity(fields: new List<FieldMetadata>
            {
                new() { Name = "recovery_rate", Alias = "recoveryRate" }
            });

            sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity,
                new[] { CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)") });

            Assert.IsTrue(sourceDefinition.Columns.ContainsKey("recovery_rate"));
            Assert.IsFalse(sourceDefinition.Columns.ContainsKey("recoveryRate"));
        }

        /// <summary>
        /// An identity fields[] entry — the documentation form that carries container and path in its
        /// description — leaves the column keyed by the alias.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_IdentityFieldEntry_KeysColumnByAlias()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            Entity entity = CreateEntity(fields: new List<FieldMetadata>
            {
                new() { Name = "recoveryRate", Description = "JSON attribute CustomAttributesJson $.RecoveryRate (decimal)" }
            });

            sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity,
                new[] { CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)") });

            Assert.IsTrue(sourceDefinition.Columns.ContainsKey("recoveryRate"));
        }

        #endregion

        #region Safe skips

        /// <summary>A physical column always wins a name collision; the attribute is skipped.</summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_AliasCollidesWithPhysicalColumn_PhysicalColumnWins()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();

            int injected = sourceDefinition.ApplyTenantVirtualColumns(
                ENTITY_NAME,
                entity: null,
                new[] { CreateJsonAttribute("name", "$.Name", "nvarchar") });

            Assert.AreEqual(0, injected);
            Assert.IsFalse(
                sourceDefinition.Columns["name"] is VirtualColumnDefinition,
                "The real column must be preserved.");
        }

        /// <summary>
        /// A container column that does not exist on the table would produce SQL referencing a missing
        /// column, so the attribute is skipped.
        /// </summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_UnknownContainerColumn_IsSkipped()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("recoveryRate", "$.RecoveryRate", "decimal(18,6)")
                with { PhysicalColumnName = "NoSuchJsonColumn" };

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
            Assert.IsFalse(sourceDefinition.Columns.ContainsKey("recoveryRate"));
        }

        /// <summary>A JSON attribute with no path cannot be projected and is skipped.</summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_MissingJsonPath_IsSkipped()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("recoveryRate", jsonPath: null!, "decimal(18,6)");

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
        }

        /// <summary>
        /// An alias that is not a plain identifier would break GraphQL schema construction, so it is
        /// rejected before it can reach the schema builder.
        /// </summary>
        [DataTestMethod]
        [DataRow("recovery rate", DisplayName = "space is rejected")]
        [DataRow("recovery-rate", DisplayName = "hyphen is rejected")]
        [DataRow("1recovery", DisplayName = "leading digit is rejected")]
        [DataRow("recovery]rate", DisplayName = "bracket is rejected")]
        public void ApplyTenantVirtualColumns_InvalidAlias_IsSkipped(string apiAlias)
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute(apiAlias, "$.Value", "nvarchar");

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
            Assert.AreEqual(3, sourceDefinition.Columns.Count, "Only the physical columns must remain.");
        }

        /// <summary>
        /// An unsupported declared type — notably a spatial type, which cannot be a JSON scalar — is
        /// skipped rather than producing an unusable field.
        /// </summary>
        [DataTestMethod]
        [DataRow("geometry", DisplayName = "geometry is skipped")]
        [DataRow("geography", DisplayName = "geography is skipped")]
        [DataRow("varbinary", DisplayName = "varbinary is skipped")]
        public void ApplyTenantVirtualColumns_UnsupportedDataType_IsSkipped(string dataType)
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("shapeAttribute", "$.Shape", dataType);

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
        }

        /// <summary>
        /// Standard columns and reserved foreign lookups are not injected: the former are served by
        /// native dab-config mappings, the latter are not projected by the engine yet.
        /// </summary>
        [DataTestMethod]
        [DataRow(TenantFieldSourceType.StandardColumn, DisplayName = "StandardColumn is not injected")]
        [DataRow(TenantFieldSourceType.ForeignLookup, DisplayName = "ForeignLookup is not injected")]
        public void ApplyTenantVirtualColumns_NonJsonAttributeSourceTypes_AreSkipped(TenantFieldSourceType fieldSourceType)
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();
            TenantSchemaField field = CreateJsonAttribute("someField", "$.Some", "nvarchar") with { FieldSourceType = fieldSourceType };

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, new[] { field }));
        }

        /// <summary>An empty field list leaves the source definition untouched.</summary>
        [TestMethod]
        public void ApplyTenantVirtualColumns_NoFields_IsNoOp()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition();

            Assert.AreEqual(0, sourceDefinition.ApplyTenantVirtualColumns(ENTITY_NAME, entity: null, System.Array.Empty<TenantSchemaField>()));
            Assert.AreEqual(3, sourceDefinition.Columns.Count);
        }

        #endregion

        #region Helpers

        private static SourceDefinition CreateSourceDefinition()
        {
            SourceDefinition sourceDefinition = new();
            sourceDefinition.Columns.Add("id", new ColumnDefinition(typeof(int)) { DbType = DbType.Int32 });
            sourceDefinition.Columns.Add("name", new ColumnDefinition(typeof(string)) { DbType = DbType.String, SqlTypeName = "nvarchar" });
            sourceDefinition.Columns.Add(CONTAINER_COLUMN, new ColumnDefinition(typeof(string)) { DbType = DbType.String, SqlTypeName = "nvarchar", IsNullable = true });
            sourceDefinition.PrimaryKey.Add("id");
            return sourceDefinition;
        }

        private static TenantSchemaField CreateJsonAttribute(string apiAlias, string jsonPath, string dataType)
            => new()
            {
                FieldId = 1,
                TenantId = TENANT_ID,
                EntityName = ENTITY_NAME,
                FieldSourceType = TenantFieldSourceType.JsonAttribute,
                PhysicalColumnName = CONTAINER_COLUMN,
                JsonPath = jsonPath,
                ApiAlias = apiAlias,
                DataType = dataType,
                DisplayName = apiAlias,
                IsVisible = true,
                IsReadOnly = false
            };

        private static Entity CreateEntity(
            Dictionary<string, string>? mappings = null,
            List<FieldMetadata>? fields = null)
            => new(
                Source: new EntitySource(Object: "dbo.assay", Type: EntitySourceType.Table, Parameters: null, KeyFields: null),
                GraphQL: new(Singular: ENTITY_NAME, Plural: ENTITY_NAME),
                Rest: new(Enabled: true),
                Permissions: System.Array.Empty<EntityPermission>(),
                Relationships: null,
                Mappings: mappings,
                Fields: fields);

        #endregion
    }
}
